#!/usr/bin/env node
// `npm run clean`: remove every generated output so the next build/test
// cannot silently reuse stale artifacts (§4-5).
import { rmSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const targets = [
  "dist",
  "coverage",
  // generated-but-gitignored sources (regenerated by gen:identity / prebuild)
  join("packages", "core", "src", "release.gen.ts"),
];
for (const t of targets) {
  const p = join(ROOT, t);
  if (existsSync(p)) {
    rmSync(p, { recursive: true, force: true });
    console.log(`clean: removed ${t}`);
  } else {
    console.log(`clean: absent ${t} (ok)`);
  }
}
